#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# commitされたts,tsxファイルを取得
files=`git log HEAD^..HEAD --name-only --oneline | grep -E "*.ts|tsx$"`

if [ -n ${files} && ${#files(@)} > 0 ]; then
  echo "[pre-push] Find *.tx|tsx, Exec Typechecking"

  yarn tsc
  ret=$?
  if [ $ret != 0 ]; then
    echo "[pre-commit] Typechecking error."
    exit $ret
  fi
fi

exit 0
